import requests
from concurrent.futures import ThreadPoolExecutor
import threading

url = "http://173.16.0.43:8001/api/v1/scheduler/"

# url = "https://nest.scrapehero.com/api/v1/scheduler/"

ch = {'Authorization': 'Token 741ab1c7b342580b3f5b7baf19837a78539d475c'}
# pdn
# ch = {'Authorization': 'Token b837cbb1fe1618ed693b2f72c646fe90ebd2531c'}


pay = {"action": "start", "spider_id": 384, "schedule_name": "8b027f931497482e96af0ea27036f552"}

# pay = {"action": "start", "spider_id": 3226, "schedule_name": "3b338eb683804614b7c348d24f3fe2d2"}
# i = 0
# while i< 25:
#     r = requests.post(url, json=pay, headers=ch)
#     i +=1
#     print(r, r.content)

def t(i):
    r = requests.post(url, json=pay, headers=ch)
    # print(i)
    print(r)
    return r


for i in range(500):
    th = threading.Thread(target=t, args=(i,))
    th.start()
# def main():
#     print('starting')
#     # executor = ThreadPoolExecutor(20)
#     with ThreadPoolExecutor(max_workers=1) as executor:
#         pool = executor.map(t)
#         pool.send
#         # print(dir(pool))
#         i = 0
#         while i < 500:
#             i +=1
#             print(i)
#             d = executor.submit(t)
#             print(d.result())
#             d = executor.submit(t)
#             print(d.result())
#             d = executor.submit(t)
#             print(d.result())
#             d = executor.submit(t)
#             print(d.result())
#         # print(future.result())
#         # i = 0
#         # while i < 5:
#         #     i +=1
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())

#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())

#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())
#         #     future = executor.submit(t)
#         #     print(future.done())
#         #     print(future.result())

# if __name__ == '__main__':
#     print('here')
#     main()